# Generated by Django 5.1.2 on 2024-11-06 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('hotels', '0008_room_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedroom',
            name='room_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotels.roomtype'),
        ),
    ]
