# Generated by Django 5.1.2 on 2024-11-06 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookedroom_room_type'),
        ('hotels', '0008_room_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='11111', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='111123132', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(default='1111', max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='surname',
            field=models.CharField(default='jdnjfn', max_length=255),
        ),
        migrations.AlterField(
            model_name='bookedroom',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.roomtype'),
        ),
    ]
