# Generated by Django 5.1.2 on 2024-11-02 20:20

import django.core.validators
import django.db.models.deletion
import hotels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Название удобства')),
            ],
            options={
                'verbose_name': 'Удобство',
                'verbose_name_plural': 'Удобства',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер комнаты')),
                ('preview', models.ImageField(blank=True, null=True, upload_to=hotels.models.room_preview_directory_path, verbose_name='Главное фото номера')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=hotels.models.room_photo_directory_path, verbose_name='Фотография номера')),
            ],
            options={
                'verbose_name': 'Фотография номера',
                'verbose_name_plural': 'Фотографии номера',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название типа номера')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание типа номера')),
                ('occupancy', models.PositiveIntegerField(verbose_name='Максимальное количество гостей')),
            ],
            options={
                'verbose_name': 'Тип номера',
                'verbose_name_plural': 'Типы номеров',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название отеля')),
                ('address', models.CharField(max_length=80, verbose_name='Адрес отеля')),
                ('city', models.CharField(max_length=70, verbose_name='Город')),
                ('country', models.CharField(max_length=70, verbose_name='Страна')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание отеля')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Рейтинг отеля')),
                ('preview', models.ImageField(blank=True, null=True, upload_to=hotels.models.hotel_preview_directory_path, verbose_name='Главное фото отеля')),
                ('amenities', models.ManyToManyField(blank=True, related_name='hotels', to='hotels.amenity', verbose_name='Удобства отеля')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=hotels.models.hotel_photo_directory_path, verbose_name='Фотография отеля')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_images', to='hotels.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Фотография отеля',
                'verbose_name_plural': 'Фотографии отеля',
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='hotels', to='hotels.hotelimage', verbose_name='Фотографии отеля'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotels.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
