# Generated by Django 5.1.2 on 2024-11-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена за ночь'),
        ),
    ]
