# Generated by Django 5.1.2 on 2024-11-04 19:00

import hotels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_roomtype_price_per_night'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='images',
        ),
        migrations.RemoveField(
            model_name='room',
            name='preview',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='hotels.roomimage', verbose_name='Фотографии номера'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=hotels.models.room_preview_directory_path, verbose_name='Главное фото номера'),
        ),
    ]
