# Generated by Django 5.1.2 on 2024-11-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_remove_room_images_remove_room_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='max_guests',
            field=models.PositiveIntegerField(default=1, verbose_name='Максимальное количество гостей'),
        ),
    ]
