# Generated by Django 5.1.2 on 2024-11-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_remove_roomtype_max_guests_alter_roomtype_occupancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='check_in_time',
            field=models.TimeField(default='14:00', verbose_name='Время заселения'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_out_time',
            field=models.TimeField(default='12:00', verbose_name='Время выселения'),
        ),
    ]
